name: Build

on:
  push:
    paths:
      - build.gradle
      - settings.gradle
      - src/**
      - launcher/build.gradle
      - launcher/src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: antville

    strategy:
      matrix:
        java: [11, 17, 21]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: https://github.com/actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile with Gradle
        run: ./gradlew :compileJava
