name: Build

on:
  push:
    paths:
      - .github/workflows/build.yml
      - build.gradle
      - settings.gradle
      - src/**
      - launcher/build.gradle
      - launcher/src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: antville

    steps:
      - uses: actions/checkout@v4

      - name: Compile with Gradle
        run: ./gradlew :compileJava
