name: Deploy (Production)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: antville

    environment:
      name: weblogs.at
      url: https://weblogs.at

    steps:
      - name: Copy files to production server
        run: ssh staging-server deploy-helma
