name: Deploy (Production)

on: 
  workflow_dispatch:
    inputs:
      hostname:
        description: Hostname
        type: string
        required: true
        default: antville.org

jobs:
  deploy:
    runs-on: antville

    steps:
      - name: Copy files to production server
        run: ssh ${{ inputs.hostname }} deploy-helma
