name: Deploy

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: Hostname
        type: string
        required: true
        default: antville.org

jobs:
  stage:
    runs-on: antville

    environment:
      name: production
      url: ${{ inputs.hostname }}

    steps:
      - uses: actions/checkout@v6

      - name: Compute variables
        run: |
          date="$(TZ=UTC git show --no-patch --format='%ad' --date=format-local:'%-d %b %Y, %H:%M:%S %Z' $GITHUB_SHA)"
          sha="$(git rev-parse --short HEAD)"
          message="Deployment $GITHUB_RUN_NUMBER of $GITHUB_REPOSITORY at $sha ($date)"
          echo "message=$message" >> $GITHUB_ENV

      - name: Save local changes
        run: ssh ${{ inputs.hostname }} commit 'Save local changes before next deployment'

      - name: Build with Gradle
        run: ./gradlew installDist

      - name: Copy build files to server
        run: |
          rsync ./build/install/helma/ ${{ inputs.hostname }}:./ \
            --verbose --archive --delete --compress \
            --filter '+ /bin' \
            --filter '+ /extras' \
            --filter '+ /launcher.jar' \
            --filter '- /lib/ext' \
            --filter '+ /lib' \
            --filter '+ /modules' \
            --filter '- /*'

      - name: Commit deployed changes
        run: ssh ${{ inputs.hostname }} commit "$message"

      - name: Restart Helma
        run: ssh ${{ inputs.hostname }} restart
