name: Deploy (Staging)

on: workflow_dispatch

jobs:
  stage:
    runs-on: antville

    environment:
      name: stage
      url: ${{ vars.stage_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew installDist

      - name: Publish to staging server
        run: |
          rsync ./build/install/helma/ staging-server:./ \
            --verbose --archive --delete --compress \
            --filter '+ /bin' \
            --filter '+ /extras' \
            --filter '+ /launcher.jar' \
            --filter '- /lib/ext' \
            --filter '+ /lib' \
            --filter '+ /modules' \
            --filter '- /*'

      - name: Restart Helma
        run: ssh staging-server restart
