name: Deploy to Antville.org development environment

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://antville-test.click

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew installDist
