name: Deploy (Staging)

on:
  workflow_dispatch

jobs:
  stage:
    runs-on: ubuntu-latest

    environment:
      name: stage
      url: https://antville-test.click

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew installDist

      - uses: ./.github/workflows/ssh.yml
        with:
          config: ${{ vars.SSH_CONFIG }}
          known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
        secrets: inherit

      - name: Publish to staging server
        # The rsync command applies the same filters as the one in tools/extras/deploy.sh
        run: |
          ssh antville.dev ping
          echo rsync ./build/install/helma/ antville.dev:./ \
            --verbose --archive --delete --compress \
            --filter 'protect /lib/ext' \
            --filter '+ /launcher.jar' \
            --filter '+ /lib' \
            --filter '- /*' \

      - name: Restart Helma
        run: ssh antville.dev restart
